{{- if and .Values.replicaSet.enabled .Values.replicaSet.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-create-replicaset-initiate-job" (include "mongodb.name" .) | trunc 53 | trimSuffix "-" }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    helm.sh/hook-weight: "100"
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: "replicaset-initiate-job"
      {{- with .Values.commonPodAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.commonPodLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ printf "%s-create-replicaset-initiate-job" (include "mongodb.name" .) | trunc 53 | trimSuffix "-" }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/scripts/replicaset.sh"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if eq .Values.config.security.authorization "enabled" }}
            - name: MONGO_AUTHENTICATION_ENABLED
              value: "true"
            {{- end }}
            {{- if or .Values.createUsers (eq .Values.config.security.authorization "enabled") }}
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if .Values.useExistingSecret.enabled }}
                  name: {{ .Values.useExistingSecret.name }}
                  {{- else }}
                  name: {{ template "mongodb.fullname" . }}
                  {{- end }}
                  key: mongodb-root-username
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.useExistingSecret.enabled }}
                  name: {{ .Values.useExistingSecret.name }}
                  {{- else }}
                  name: {{ template "mongodb.fullname" . }}
                  {{- end }}
                  key: mongodb-root-password
            - name: MONGO_SERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if .Values.useExistingSecret.enabled }}
                  name: {{ .Values.useExistingSecret.name }}
                  {{- else }}
                  name: {{ template "mongodb.fullname" . }}
                  {{- end }}
                  key: mongodb-service-username
            - name: MONGO_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.useExistingSecret.enabled }}
                  name: {{ .Values.useExistingSecret.name }}
                  {{- else }}
                  name: {{ template "mongodb.fullname" . }}
                  {{- end }}
                  key: mongodb-service-password
            - name: MONGO_DEVELOPER_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if .Values.useExistingSecret.enabled }}
                  name: {{ .Values.useExistingSecret.name }}
                  {{- else }}
                  name: {{ template "mongodb.fullname" . }}
                  {{- end }}
                  key: mongodb-developer-username
            - name: MONGO_DEVELOPER_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.useExistingSecret.enabled }}
                  name: {{ .Values.useExistingSecret.name }}
                  {{- else }}
                  name: {{ template "mongodb.fullname" . }}
                  {{- end }}
                  key: mongodb-developer-password
            {{- end }}
          volumeMounts:
            - name: {{ include "mongodb.name" . }}-script-config
              mountPath: /scripts
            {{- if .Values.createUsers }}
            - name: {{ include "mongodb.name" . }}-setup-scripts
              mountPath: /setup-scripts
            {{- end }}
          {{- with .Values.replicaSet.job.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "mongodb.name" . }}-script-config
          configMap:
            name: {{ template "mongodb.fullname" . }}-script-configmap
            defaultMode: 0555
        {{- if .Values.createUsers }}
        - name: {{ include "mongodb.name" . }}-setup-scripts
          configMap:
            name: {{ template "mongodb.fullname" . }}-setup-scripts
            defaultMode: 0555
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
