apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.createPasswordsSecret }}
  mongodb-root-username: {{ .Values.mongodbRootUsername | default "root" | b64enc | quote }}
  mongodb-service-username: {{ .Values.mongodbServiceUsername | default "service-user-mongo" | b64enc | quote }}
  mongodb-developer-username: {{ .Values.mongodbDeveloperUsername | default "developer-user-mongo" | b64enc | quote }}
  mongodb-root-password:  {{ .Values.mongodbRootPassword | required "Root User password required." | b64enc | quote }}
  mongodb-service-password:  {{ .Values.mongodbServicePassword | required "Serivce User password required." | b64enc | quote }}
  mongodb-developer-password:  {{ .Values.mongodbDeveloperPassword | required "Developer User password required." | b64enc | quote }}
  {{- end }}
  {{- if and .Values.replicaSet.enabled (eq .Values.config.security.authorization "enabled") }}
  {{- if .Values.replicaSet.key }}
  mongodb-replica-set-key:  {{ .Values.replicaSet.key | b64enc | quote }}
  {{- else }}
  mongodb-replica-set-key: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- end }}
