apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.createPasswordsSecret -}}
  mongodb-root-username: {{ .Values.mongodbRootUsername | b64enc | quote }}
  mongodb-service-username: {{ .Values.mongodbServiceUsername | b64enc | quote }}
  monogdb-developer-username: {{ .Values.mongodbDeveloperUsername | b64enc | quote }}
  {{- if .Values.mongodbRootPassword }}
  mongodb-root-password:  {{ .Values.mongodbRootPassword | b64enc | quote }}
  {{- else }}
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbServicePassword }}
  mongodb-service-password:  {{ .Values.mongodbServicePassword | b64enc | quote }}
  {{- else }}
  mongodb-service-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbDeveloperPassword }}
  mongodb-developer-password:  {{ .Values.mongodbDeveloperPassword | b64enc | quote }}
  {{- else }}
  mongodb-developer-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.replicaSet.enabled (eq .Values.config.security.authorization "enabled") }}
  {{- if .Values.replicaSet.key }}
  mongodb-replica-set-key:  {{ .Values.replicaSet.key | b64enc | quote }}
  {{- else }}
  mongodb-replica-set-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
