{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-exporter.fullname" . }}
  labels:
    app: {{ include "mongodb-exporter.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ include "mongodb.chart" . }}
  annotations:
    {{- toYaml .Values.exporter.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.exporter.replicas }}
  selector:
    matchLabels:
      app: {{ include "mongodb-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if or .Values.exporter.podAnnotations .Values.commonPodAnnotations }}
      annotations:
        {{- with .Values.exporter.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonPodAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        app: {{ include "mongodb-exporter.name" . }}
        release: {{ .Release.Name }}
        {{- with .Values.commonPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "mongodb.serviceAccountName" . }}
      containers:
        - name: mongodb-exporter
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-exporter.fullname" . }}
                  key: mongodb-uri
            {{- if .Values.exporter.env }}
            {{- range $key, $value := .Values.exporter.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          args:
            - --web.listen-address={{ printf ":%s" .Values.exporter.port }}
            {{- toYaml .Values.exporter.extraArgs | nindent 12 }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.exporter.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.exporter.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.exporter.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
          {{- with .Values.exporter.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      affinity:
        {{- toYaml .Values.exporter.affinity | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.exporter.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.exporter.nodeSelector | nindent 8 }}
      {{- if .Values.exporter.priorityClassName }}
      priorityClassName: {{ .Values.exporter.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      tolerations:
        {{- toYaml .Values.exporter.tolerations | nindent 8 }}
      {{- with .Values.exporter.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
